"""add_all_executive_fields

Revision ID: 18c740eb7a75
Revises: 30f5f1395e2c
Create Date: 2026-02-01 19:29:50.853134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18c740eb7a75'
down_revision: Union[str, Sequence[str], None] = '30f5f1395e2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('executives', schema=None) as batch_op:
        batch_op.alter_column('work_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_executives_full_name'))
        batch_op.drop_index(batch_op.f('ix_executives_work_email'))
        batch_op.create_index(batch_op.f('ix_executives_work_email'), ['work_email'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('executives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_executives_work_email'))
        batch_op.create_index(batch_op.f('ix_executives_work_email'), ['work_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_executives_full_name'), ['full_name'], unique=False)
        batch_op.alter_column('address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('work_email',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
