"""mapeamento_executivos

Revision ID: 2c8956da521b
Revises: 18c740eb7a75
Create Date: 2026-02-03 17:47:01.263926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c8956da521b'
down_revision: Union[str, Sequence[str], None] = '18c740eb7a75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('executives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('street', sa.Text(), nullable=True))
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('executives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.TEXT(), nullable=True))
        batch_op.drop_column('street')

    # ### end Alembic commands ###
