"""recriando_banco_completo

Revision ID: 30f5f1395e2c
Revises: 
Create Date: 2026-01-27 18:35:58.977777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30f5f1395e2c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('neighborhood', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zipCode', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('legal_organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_legal_organizations_cnpj'), ['cnpj'], unique=True)
        batch_op.create_index(batch_op.f('ix_legal_organizations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_organizations_name'), ['name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=False)

    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('legalOrganizationId', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('neighborhood', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zipCode', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['legalOrganizationId'], ['legal_organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_cnpj'), ['cnpj'], unique=True)
        batch_op.create_index(batch_op.f('ix_organizations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_name'), ['name'], unique=False)

    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('organizationId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organizationId'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'organizationId', name='_name_organization_uc')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_id'), ['id'], unique=False)

    op.create_table('executives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('rg', sa.String(), nullable=True),
    sa.Column('rg_issuer', sa.String(), nullable=True),
    sa.Column('rg_issue_date', sa.Date(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('place_of_birth', sa.String(), nullable=True),
    sa.Column('mother_name', sa.String(), nullable=True),
    sa.Column('father_name', sa.String(), nullable=True),
    sa.Column('civil_status', sa.String(), nullable=True),
    sa.Column('work_email', sa.String(), nullable=True),
    sa.Column('work_phone', sa.String(), nullable=True),
    sa.Column('extension', sa.String(), nullable=True),
    sa.Column('personal_email', sa.String(), nullable=True),
    sa.Column('personal_phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('linkedin_profile_url', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('cost_center', sa.String(), nullable=True),
    sa.Column('employee_id', sa.String(), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('work_location', sa.String(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('reports_to_executive_id', sa.Integer(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('education', sa.Text(), nullable=True),
    sa.Column('languages', sa.String(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(), nullable=True),
    sa.Column('emergency_contact_relation', sa.String(), nullable=True),
    sa.Column('dependents_info', sa.Text(), nullable=True),
    sa.Column('bank_info', sa.Text(), nullable=True),
    sa.Column('compensation_info', sa.Text(), nullable=True),
    sa.Column('system_access_levels', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['reports_to_executive_id'], ['executives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('executives', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_executives_cpf'), ['cpf'], unique=True)
        batch_op.create_index(batch_op.f('ix_executives_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_executives_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_executives_work_email'), ['work_email'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('executives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_executives_work_email'))
        batch_op.drop_index(batch_op.f('ix_executives_id'))
        batch_op.drop_index(batch_op.f('ix_executives_full_name'))
        batch_op.drop_index(batch_op.f('ix_executives_cpf'))

    op.drop_table('executives')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_id'))

    op.drop_table('departments')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_name'))
        batch_op.drop_index(batch_op.f('ix_organizations_id'))
        batch_op.drop_index(batch_op.f('ix_organizations_cnpj'))

    op.drop_table('organizations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('legal_organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_legal_organizations_name'))
        batch_op.drop_index(batch_op.f('ix_legal_organizations_id'))
        batch_op.drop_index(batch_op.f('ix_legal_organizations_cnpj'))

    op.drop_table('legal_organizations')
    # ### end Alembic commands ###
