"""adicionando novas tabelas

Revision ID: 31dbd41483d4
Revises: 64e4607e52fc
Create Date: 2025-11-05 18:11:52.466903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31dbd41483d4'
down_revision: Union[str, Sequence[str], None] = '64e4607e52fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('neighborhood', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zipCode', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_organizations_cnpj'), 'legal_organizations', ['cnpj'], unique=True)
    op.create_index(op.f('ix_legal_organizations_id'), 'legal_organizations', ['id'], unique=False)
    op.create_index(op.f('ix_legal_organizations_name'), 'legal_organizations', ['name'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('legalOrganizationId', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('neighborhood', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zipCode', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['legalOrganizationId'], ['legal_organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_cnpj'), 'organizations', ['cnpj'], unique=True)
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('organizationId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organizationId'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'organizationId', name='_name_organization_uc')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_cnpj'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_legal_organizations_name'), table_name='legal_organizations')
    op.drop_index(op.f('ix_legal_organizations_id'), table_name='legal_organizations')
    op.drop_index(op.f('ix_legal_organizations_cnpj'), table_name='legal_organizations')
    op.drop_table('legal_organizations')
    # ### end Alembic commands ###
