"""Política de senha alinhada a NIST SP 800-63B / OWASP (senhas memorizadas)."""

MIN_LENGTH = 8
MAX_LENGTH = 64

COMMON_PASSWORDS: frozenset[str] = frozenset(
    {
        "12345678",
        "123456789",
        "1234567890",
        "password",
        "password1",
        "password123",
        "senha123",
        "senha1234",
        "qwerty123",
        "qwertyui",
        "abc12345",
        "admin123",
        "letmein1",
        "welcome1",
        "iloveyou",
        "sunshine",
        "princess",
        "football",
        "baseball",
        "dragon12",
        "master12",
        "monkey12",
        "shadow12",
        "trustno1",
        "batman12",
        "superman",
        "starwars",
        "whatever",
        "passw0rd",
        "p@ssw0rd",
        "changeme",
        "executiva",
        "executiva1",
        "executiva123",
        "hmr12345",
        "administrador",
        "brasil123",
        "flamengo",
        "corinthians",
        "palmeiras",
        "santos123",
        "gremio123",
        "vasco1234",
        "botafogo",
        "familia123",
        "amor1234",
        "felicidade",
        "computador",
        "internet",
        "seguranca",
        "minhasenha",
        "minhasenha1",
        "meusenha1",
        "usuario1",
        "usuario123",
        "cliente123",
        "empresa123",
        "acesso123",
        "sistema123",
        "cadastro1",
        "cadastro123",
        "11111111",
        "00000000",
        "87654321",
        "987654321",
        "asdfghjk",
        "zxcvbnm1",
        "qazwsxedc",
        "1q2w3e4r",
        "1qaz2wsx",
        "aa123456",
        "abc123456",
        "teste123",
        "teste1234",
        "test1234",
        "demo1234",
        "guest123",
        "welcome123",
        "hello123",
        "access123",
        "login1234",
        "senha@123",
        "P@ssw0rd",
        "Password1",
        "Password123",
        "Admin1234",
        "Qwerty123",
        "Brasil123",
        "Santos123",
        "Flamengo1",
        "Corinthians",
        "Palmeiras",
        "Gremio123",
        "Vasco1234",
        "Familia123",
        "Amor12345",
        "Felicidade",
        "Computador",
        "Internet1",
        "Seguranca",
        "Minhasenha",
        "Meusenha1",
        "Usuario123",
        "Cliente123",
        "Empresa123",
        "Acesso123",
        "Sistema123",
        "Cadastro123",
    }
)


def validate_password(password: str) -> None:
    if len(password) < MIN_LENGTH:
        raise ValueError("A senha deve ter pelo menos 8 caracteres.")
    if len(password) > MAX_LENGTH:
        raise ValueError("A senha deve ter no máximo 64 caracteres.")
    if password.lower() in COMMON_PASSWORDS:
        raise ValueError("Esta senha é muito comum. Escolha outra.")
